### ISSUE TITLE
Email address param does not exist in login output why?

### ISSUE THREAD

**Issue by jeevan15498** [yobaji/vue3-google-login#10]
Hello, @yobaji  

Thank you for creating this amazing plugin.

I am using basic example but email address not exists in the  login output. Please tell me where I am making mistake?

```js
<script setup>
import { onMounted } from "vue";
import { useRouter } from "vue-router";
import { decodeCredential } from "vue3-google-login";

const router = useRouter();

const callback = (response) => {
  const userData = decodeCredential(response.credential);
  console.log("Handle the userData", userData);
};
</script>

<template>
  <div class="container m-5">
    <GoogleLogin :callback="callback" prompt auto-login />
  </div>
</template>
```

**Output**

```
{
  aud: "1024912902026-sbjmb3pq2n5ophqeki52vvcqhktsrkg7.apps.googleusercontent.com"
  azp: "1024912902026-sbjmb3pq2n5ophqeki52vvcqhktsrkg7.apps.googleusercontent.com"
  exp: 1658250730
  given_name: "Jeevan"
  iat: 1658247160
  iss: "https://accounts.google.com"
  jti: "ccbef55466d911b695809b569ec65299af344b5f"
  name: "Jeevan"
  nbf: 1653246830
  picture: "https://lh3.googleusercontent.com/a-/AFdXucq0Iyr4ssuNpsj7b6PHhN6-yQvgOdtpdn5AFMwGKQ=s96-c"
  sub: "100531124344843609134"
}
```

**Comment by yobaji** [comment]
@jeevan15498 I think the problem is with the client id you are using, it must have these scopes selected [email, profile, openid], please follow [these steps](https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid) while creating a client id.

**Comment by JasonMSims** [comment]
I have a similar issue - I can only get the email and not the other basic info (name, picture, etc). The OAuth consent screen is correct and I have deleted the old client ID and created a new one. I am still unable to access that info.

**Comment by jeevan15498** [comment]
Hi, @JasonMSims 

1. Go to **Google Cloud Console** and Open **APIs & Services** 
2. Open **OAuth consent screen** and Check **Scopes**

```
./auth/userinfo.email
./auth/userinfo.profile
openid
```

<img width="405" alt="image" src="https://user-images.githubusercontent.com/40597858/180110686-42729636-09e9-45d2-bb8f-fcb39db9d7dd.png">

**Comment by jeevan15498** [comment]
This was my problem in which email param was not coming in the output, it was that I was already logged in to Google Account in Chrome browser but when I logged out of the account and login again, the email param started showing

**Comment by JasonMSims** [comment]
Upon further testing, this issue actually only appears on my primary login that I have been using. I just tested with a different login and the information is present.
