### ISSUE TITLE
Set token failed. Gapi.client.setToken undefined error

### ISSUE THREAD

**Issue by ignasv** [yobaji/vue3-google-login#11]
I'm using a custom button with `popup-type="TOKEN"`. Response comes in ok, but I also get a warning in the console:
`[Warning] [GSI_LOGGER-TOKEN_CLIENT]: Set token failed. Gapi.client.setToken undefined. (client, line 36)`

My setup: 
```
<template>
  <GoogleLogin :callback="callback" popup-type="TOKEN">
    <button>Login Using Google</button>
  </GoogleLogin>
</template>
<script setup lang="ts">
const callback = (response: string) => {
  console.log("Handle the response", response);
};
</script>
```

**Comment by yobaji** [comment]
@ignasv I have noticed this warning, but its looks like there is no way to remove this, Its from google [library](https://developers.google.com/identity/oauth2/web/guides/load-3p-authorization-library) used under the hoods, any application using this library is having the same problem, here is a demo of a react app using the same library for google login https://react-oauth.vercel.app/ (Authorization>Implicit Flow)
