### ISSUE TITLE
npm error while trying to install package on a fresh new Quasar app

### ISSUE THREAD

**Issue by philippedasilva-orizone** [yobaji/vue3-google-login#14]
Hi,

I just started a quick new project and tried to install vue3-google-login package using npm and I get this error:
![Screenshot 2022-08-18 at 13 57 24](https://user-images.githubusercontent.com/77384971/185389218-f8658da2-d85b-4876-a1cd-b9b63c5a767c.png)

and is the end of the generated log file with the error
![image](https://user-images.githubusercontent.com/77384971/185389593-edae26cf-7316-48da-ac56-32744d2149df.png)

Anything I'm missing from requirements stand point ?

**Comment by yobaji** [comment]
@philippedasilva-orizone Can provide the steps you followed to install the Quasar app? You are using Quasar with Vue 3 right? I just tried to create a Quasar app and integrated vue3-google-login plugin and didn't faced any issues

**Comment by philippe-dasilva** [comment]
I did try again and could not find the issue anymore. Probably something I did wrong.  Thanks.
