### ISSUE TITLE
How to change google button's language

### ISSUE THREAD

**Issue by Rachael0108** [yobaji/vue3-google-login#21]
i want to change the google button's language to english ( local:  en-US)
this is my code: 
`<GoogleLogin :callback="callback"/>`
`import { decodeCredential } from 'vue3-google-login'
const callback = (response:any) => {
	let userData = decodeCredential(response.credential)
	userData = {
		account: userData.sub,
		type: 'Google',
		password: ''
	}
	emit('googleLogin', userData)
}`

any ideas ,thank u for your apply

**Comment by yobaji** [comment]
Have you used the buttonConfig option mention [here](https://yobaji.github.io/vue3-google-login/#options)
Try this

```vue
<GoogleLogin :callback="callback"  :button-config="{
    locale: 'en-US'
  }"/>

<script setup lang="ts">
import { decodeCredential } from 'vue3-google-login' 

const callback = (response: any) => {
    let userData = decodeCredential(response.credential) userData = {
        account: userData.sub,
        type: 'Google',
        password: ''
    }
    emit('googleLogin', userData)
}
</script>
```
