### ISSUE TITLE
 can vue3-google-login be used to access google drive api?

### ISSUE THREAD

**Issue by vicebp** [yobaji/vue3-google-login#31]
I am using vue3-google-login to login to my app, can it be used to access google drive api?

**Comment by yobaji** [comment]
@vicebp No, this is only meant for implementing log-in and sign-up flows using [Google Identity Services](https://developers.google.com/identity) with the help of [Google 3P Authorization JavaScript Library](https://developers.google.com/identity/oauth2/web/guides/load-3p-authorization-library)

**Comment by lucasow** [comment]
Sry for reopening closed thread. But I think you can achieve your goal with googleTokenLogin:

`
import { googleTokenLogin } from "vue3-google-login"
googleTokenLogin()
.then((response)=>{
   let token = response.access_token // this token you can use to call Google Drive API
})
`

But formally yobaji has right. You cannot use this library to call Google API.
