### ISSUE TITLE
SSR issues - maybe an option to load the google code elsewhere?

### ISSUE THREAD

**Issue by acidjazz** [yobaji/vue3-google-login#4]
Loving this component  BTW - great work!

I am trying to use it nuxt3 - and even setting a plugin that is client-only, I get issues as it's trying to access `document` in nodejs:

```
[nitro] [dev] [unhandledRejection] ReferenceError: document is not defined
    at file:///Users/k/lsf/lsf/.nuxt/dist/server/server.mjs:27075:734
    at new Promise (<anonymous>)
    at $id_ad0949e7 (file:///Users/k/lsf/lsf/.nuxt/dist/server/server.mjs:27075:685)
    at async __instantiateModule__ (file:///Users/k/lsf/lsf/.nuxt/dist/server/server.mjs:38980:3)
```

Maybe if we have an option to allow the loading of the gsi/client code elsewhere? so I can make sure it's not loaded/running on the server end?

here is my plugin `plugins/google.client.ts`

```ts
import vue3GoogleLogin from 'vue3-google-login'

export default defineNuxtPlugin((nuxtApp) => {
  const config = useRuntimeConfig()
  nuxtApp.vueApp.use(vue3GoogleLogin, {
    clientId: config.public.googleClientId,
  })
})
```

and here is how I'm using it:

```ts
onMounted(() => {
  if (!$api.loggedIn.value && process.client)
    googleOneTap({autoLogin: true}).then((response) => {
      console.log(response)
    })
})
```

**Comment by acidjazz** [comment]
I think the culprit is actually here

https://github.com/yobaji/vue3-google-login/blob/c5da8965269ec835f74c952a76abac1ca8adf334/src/plugin/utils.ts#L38

**Comment by yobaji** [comment]
@acidjazz Sorry for the late reply, yes you are right that line was the culprit 😂, please try the latest version 2.0.10, I have added a small patch to fix this issue on nuxt3, hope this will resolve your issue.
