### ISSUE TITLE
Provide a way to choose beetwen showing  a popup or redirecting 

### ISSUE THREAD

**Issue by yasserss** [yobaji/vue3-google-login#8]
Is there any way i can configure these two mode , the default is popup and i cant find any way to change it

**Comment by hello-netsocks** [comment]
> @yasserss Sorry for the late reply, you can use idConfiguration option to implement redirect mode, refer the following example
> 
> ```
> <template>
>   <GoogleLogin
>     :id-configuration="{
>       login_uri: 'http://your_app_domain.com/your_page_to_handle_response_credential',
>       ux_mode: 'redirect',
>     }"
>   />
> </template>
> ```
> 
> Also make sure the login_uri must be added in the "Authorized redirect URIs" section in your google console

Hello, thanks for clarification.

However, It does not work. It keeps opening the popup everytime.

I registred the component using

```TypeScript
  app.use(vue3GoogleLogin, {
    clientId: '.....',
  }) 
```

and used it like this:

```TypeScript
  app.use(vue3GoogleLogin, {
    clientId: '.....',
  }) 
```

```TypeScript
<script>
// ...start of script.

const idConfig = {
  login_uri: `${location.origin}/netsocks/auth/sign-in`,
  ux_mode: 'redirect',
  callback,
}

// .... end of script
</script>
```
```Vue
    <GoogleLogin :idConfiguration="idConfig">
      <VBtn>
        Sign in with {{ link.name }}
      </VBtn>
    </GoogleLogin>

```

Maybe the idConfig param isn't taking effect?

**Comment by LucianoAngel** [comment]
> ```
> 
>     :id-configuration="{
>       login_uri: 'http://your_app_domain.com/your_page_to_handle_response_credential',
>       ux_mode: 'redirect',
>     }"
> ```

Same problem here.
